version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/DockerFile.prod
    command: >
      sh -c "gunicorn app.core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/var/www/mailganer/public/static
    expose:
      - 8000
    env_file:
      - ./docker/env/.env.prod
    networks:
      - backend

  redis:
    image: redis:7.0.5-bullseye
    networks:
      - backend
    expose:
      - 6379
    volumes:
      - .:/app
    container_name: redis

  celery:
    build:
      context: .
      dockerfile: docker/DockerFile.prod
    command: python -m celery -A app.core worker
    env_file:
      - ./docker/env/.env.dev
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - redis
      - app
    container_name: celery

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/mailganer/public/static
    depends_on:
      - app
    networks:
      backend:
        aliases:
          - nginx

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
