version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/DockerFile.local
    command: >
      sh -c "python app/manage.py migrate &&
             python app/manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - ./docker/env/.env.dev
    networks:
      - backend
    volumes:
      - ./app:/var/www/mailganer/app

  redis:
    image: redis:7.0.5-bullseye
    networks:
      - backend
    expose:
      - 6379
    volumes:
      - .:/app
    container_name: redis

  celery:
    build:
      context: .
      dockerfile: docker/DockerFile.prod
    command: python -m celery -A app.core worker
    env_file:
      - ./docker/env/.env.dev
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - redis
      - app
    container_name: celery

networks:
  backend:
    driver: bridge

volumes:
  static_volume:
