version: "3.9"

services:
  db:
    image: postgres:14-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./docker/env/.env.db.dev
    networks:
      - backend
    restart: always

  app:
    build:
      context: .
      dockerfile: ./docker/DockerFile.prod
    command: >
      sh -c "fab django.migrate &&
             python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/var/www/app.qurankg.com/api/app
    ports:
      - '8000:8000'
    env_file:
      - ./docker/env/.env.dev
    depends_on:
      - db
    links:
      - db:db
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
