# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-18 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmail',
            name='recipients_list',
        ),
        migrations.RemoveField(
            model_name='scheduledmail',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='scheduledmail',
            name='template',
        ),
        migrations.AddField(
            model_name='scheduledmail',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledmail',
            name='title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledmail',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 17, 9, 53, 544034, tzinfo=utc)),
        ),
    ]
