# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-19 07:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 7, 34, 27, 577581, tzinfo=utc)),
        ),
    ]
